/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DonemOdevi;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enes Behlul
 */
public class DoktorBulusmaEkrani extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    DefaultListModel dlm = new DefaultListModel();
    int doktorId;

    /**
     * Creates new form DoktorBulusmaEkrani
     */
    public DoktorBulusmaEkrani() {
        initComponents();
        dtm.addColumn("Bulusma Tarihlerim");
        dtm.addColumn("Gelecek Hasta");
        tblDoktorBulusmalar.setModel(dtm);
    }

    public DoktorBulusmaEkrani(Doktor_1 girisYapanDoktor) {
        initComponents();
        doktorId = girisYapanDoktor.getDoktorId();
        this.setTitle(girisYapanDoktor.getDoktorAdi() + " " + girisYapanDoktor.getDoktorSoyadi());
        dtm.addColumn("Bulusma Tarihlerim");
        dtm.addColumn("Gelecek Hasta");
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("RandevuVeriTabanliPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT d FROM Bulusma_1 d WHERE d.doktorId=:DID");
        q.setParameter("DID", girisYapanDoktor.getDoktorId());
        List<Bulusma_1> bulusmalarim = q.getResultList();
        for (Bulusma_1 bulusma : bulusmalarim) {
            dtm.addRow(new Object[]{bulusma.getTarih(), bulusma.getKisiAdi()});
        }
        tblDoktorBulusmalar.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoktorBulusmalar = new javax.swing.JTable();
        btnCikisYap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSeciliRandevuyuSil = new javax.swing.JButton();
        txtSorgu = new javax.swing.JTextField();
        btnSorgula = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDoktorBulusmalar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDoktorBulusmalar);

        btnCikisYap.setText("Çıkış");
        btnCikisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisYapActionPerformed(evt);
            }
        });

        jLabel1.setText("Randevularım:");

        btnSeciliRandevuyuSil.setText("Seçili randevuyu sil");
        btnSeciliRandevuyuSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeciliRandevuyuSilActionPerformed(evt);
            }
        });

        btnSorgula.setText("Sorgula");
        btnSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorgulaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSeciliRandevuyuSil)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(335, 335, 335)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(276, 276, 276)
                                .addComponent(btnCikisYap)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSorgu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSorgula)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSeciliRandevuyuSil)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSorgu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSorgula))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCikisYap)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCikisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisYapActionPerformed
        // TODO add your handling code here:
        KullaniciGiris k = new KullaniciGiris();
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCikisYapActionPerformed

    private void btnSeciliRandevuyuSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeciliRandevuyuSilActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("RandevuVeriTabanliPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("DELETE FROM Bulusma_1 b WHERE b.tarih=:TDID");
        if (tblDoktorBulusmalar.isRowSelected(tblDoktorBulusmalar.getSelectedRow())) {
            q.setParameter("TDID", dtm.getValueAt(tblDoktorBulusmalar.getSelectedRow(), 0));

            em.getTransaction().begin();
            q.executeUpdate();
            em.getTransaction().commit();

            em.close();
            emf.close();
            dtm.removeRow(tblDoktorBulusmalar.getSelectedRow());
        }


    }//GEN-LAST:event_btnSeciliRandevuyuSilActionPerformed

    private void btnSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorgulaActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("RandevuVeriTabanliPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT d FROM Bulusma_1 d WHERE d.doktorId=:DID");
        q.setParameter("DID", doktorId);
        List<Bulusma_1> bulusmalarim = q.getResultList();
        String desen = txtSorgu.getText();
        Pattern pattern = Pattern.compile(desen);
        
        for (Bulusma_1 bulusma : bulusmalarim) {
            Matcher m = pattern.matcher(bulusma.getTarih()+" "+bulusma.getKisiAdi());
            while (m.find()) {
                dlm.addElement(bulusma.getTarih()+" "+ bulusma.getKisiAdi());
            }
            jList1.setModel(dlm);
        }
        String cumle = "Fatih123  Sultan1 Mehmet113 vakif4 Universitesi5 ";

        int sayaac = 0;
//        while (m.find()) {
//            System.out.println(m.group());
//        }
//        System.out.println(sayaac);
    }//GEN-LAST:event_btnSorgulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorBulusmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorBulusmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorBulusmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorBulusmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorBulusmaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikisYap;
    private javax.swing.JButton btnSeciliRandevuyuSil;
    private javax.swing.JButton btnSorgula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDoktorBulusmalar;
    private javax.swing.JTextField txtSorgu;
    // End of variables declaration//GEN-END:variables
}
